### ISSUE TITLE
声音的后端PulseAudio DBus挂了

### ISSUE THREAD

**Issue by xiangzhai** [martyr-deepin/deepin-system-settings#27]
connect to dbus server error.
dbus connect error
PulseAudio dbus error: ---------------------------------------------
Traceback (most recent call last):
  File "/home/zhaixiang/Projects/deepin-system-settings/modules/sound/src/settings.py", line 56, in <module>
    PA_CORE = core.Core()
  File "/home/zhaixiang/Projects/deepin-system-settings/modules/sound/src/core.py", line 59, in **init**
    self.listen_for_signal("", dbus.Array([], signature = 'o'))
  File "/home/zhaixiang/Projects/deepin-system-settings/modules/sound/src/core.py", line 271, in listen_for_signal
    self.call_async("ListenForSignal", signal, objects)
  File "/home/zhaixiang/Projects/deepin-system-settings/modules/sound/src/pulseaudio.py", line 145, in call_async
    return apply(getattr(self.dbus_interface, method_name), args, kwargs)
AttributeError: 'Core' object has no attribute 'dbus_interface'

**Comment by yilang2007lw** [comment]
dbus服务连接失败的时候，代码再重新尝试连接一次。

**Comment by xiangzhai** [comment]
我来写个PulseAudio的Python Binding
