### ISSUE TITLE
点击进入网络设置后出现以下error导致密码获取失败。

### ISSUE THREAD

**Issue by cursorzz** [martyr-deepin/deepin-system-settings#37]
Traceback (most recent call last):
  File "/home/zzpc/Project/deepin-system-settings/modules/network/src/nmlib/nm_secret_agent.py", line 100, in get_conn_priority
    if keyring.get_password(conn_priority, username):
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 37, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 199, in get_password
    assert prompt == "/"
AssertionError
Traceback (most recent call last):
  File "/home/zzpc/Project/deepin-system-settings/modules/network/src/nmlib/nm_secret_agent.py", line 114, in save_conn_priority
    keyring.set_password(conn_priority, username, str(priority))
  File "/usr/lib/python2.7/dist-packages/keyring/core.py", line 42, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python2.7/dist-packages/keyring/backend.py", line 234, in set_password
    True)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(_args, *_keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection

**Comment by yilang2007lw** [comment]
系统默认密钥环没有解锁
