### ISSUE TITLE
系统设置进入子模块失败

### ISSUE THREAD

**Issue by yilang2007lw** [martyr-deepin/deepin-system-settings#48]
Building Trie...
loading model from cache
loading model cost  0.883442878723 seconds.
Trie has been built succesfully.
class BuildIndexThread got error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dtk-0.1-py2.7.egg/dtk/ui/iconview.py", line 117, in <lambda>
    self.connect("single-click-item", lambda view, item, x, y: item.icon_item_single_click(x, y))
  File "/home/yilang/Project/deepin-software/deepin-system-settings/dss/navigate_page.py", line 279, in icon_item_single_click
    self.start_callback(self.module_info.path, self.module_info.config)
  File "dss/main.py", line 368, in <lambda>
    navigate_page = NavigatePage(module_infos, lambda path, config: start_module_process(slider, content_page_info, path, config))
  File "dss/main.py", line 272, in start_module_process
    subprocess.Popen("python %s" % (os.path.join(module_path, module_config.get("main", "program"))), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1143, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] 无法分配内存

**Comment by xiangzhai** [comment]
内存无法分配咯？！

**Comment by smallevilbeast** [comment]
我也遇到过  ......
