### ISSUE TITLE
无线网络重新连接不正常

### ISSUE THREAD

**Issue by iceleaf916** [martyr-deepin/deepin-system-settings#78]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 604, in msg_reply_handler
    reply_handler(_message.get_args_list(_*get_args_opts))
  File "/usr/share/deepin-system-settings/modules/network/src/nmlib/nmclient.py", line 166, in activate_finish
    self.emit("activate-succeed", active.get_connection().object_path)
  File "/usr/share/deepin-system-settings/modules/network/src/nmlib/nm_active_connection.py", line 47, in get_connection
    return cache.getobject(self.properties["Connection"])
  File "/usr/share/deepin-system-settings/modules/network/src/nmlib/nmcache.py", line 193, in getobject
    self.putobject(path, self.new_object(path))
  File "/usr/share/deepin-system-settings/modules/network/src/nmlib/nmcache.py", line 43, in new_object
    raise NewObjectFailed(path)
nmlib.nmcache.NewObjectFailed: 'NewObjectFailed:'

重连，网络断开，连接图标一直显示正在连接

**Comment by cursorzz** [comment]
好吧，这是我把托盘推上去的后果， 现在托盘应该被注释掉了。正在尝试修复

**Comment by 21wmd** [comment]
什么时候可以修复这个问题？
我已经被万恶的无线连接折腾死了
