### ISSUE TITLE
切换至xfce运行dss/main.py 报错

### ISSUE THREAD

**Issue by cursorzz** [martyr-deepin/deepin-system-settings#9]
Traceback (most recent call last):
  File "./main.py", line 203, in <module>
    DBusService(action_bar, content_page_info)
  File "./main.py", line 49, in **init**
    bus_name = dbus.service.BusName(APP_DBUS_NAME, bus=dbus.SessionBus())
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.**new**(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in **new**
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoServer: Failed to connect to socket /tmp/dbus-ECNEEOvG3X: Connection refused

**Comment by cursorzz** [comment]
问题似乎和byobu有关

**Comment by yilang2007lw** [comment]
$ unset DBUS_SESSION_BUS_ADDRESS
$ export DBUS_SESSION_BUS_ADDRESS

Hope this helps.

**Comment by xiangzhai** [comment]
我在电源管理的时候也有类似的问题呀，从“休眠”唤醒，貌似有些相关服务就需要“重启”咯。。。
